package TemperatureApp;


/**
* TemperatureApp/_TemperatureServiceStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TemperatureService.idl
* Monday, 23 June 2025 04:32:24 o'clock WET
*/

public class _TemperatureServiceStub extends org.omg.CORBA.portable.ObjectImpl implements TemperatureApp.TemperatureService
{

  public void sendTemperature (String id, String capteur_id, float temperature)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("sendTemperature", true);
                $out.write_string (id);
                $out.write_string (capteur_id);
                $out.write_float (temperature);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                sendTemperature (id, capteur_id, temperature        );
            } finally {
                _releaseReply ($in);
            }
  } // sendTemperature


  /*permet à un client de récupérer les dernières températures d�"un capteur donné.*/
  public float[] getLastTemperatures (String id, String capteur_id, int count)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getLastTemperatures", true);
                $out.write_string (id);
                $out.write_string (capteur_id);
                $out.write_long (count);
                $in = _invoke ($out);
                float $result[] = TemperatureApp.FloatSeqHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getLastTemperatures (id, capteur_id, count        );
            } finally {
                _releaseReply ($in);
            }
  } // getLastTemperatures

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:TemperatureApp/TemperatureService:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _TemperatureServiceStub
