package TemperatureApp;


/**
* TemperatureApp/FloatSeqHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TemperatureService.idl
* Monday, 23 June 2025 04:32:24 o'clock WET
*/

public final class FloatSeqHolder implements org.omg.CORBA.portable.Streamable
{
  public float value[] = null;

  public FloatSeqHolder ()
  {
  }

  public FloatSeqHolder (float[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = TemperatureApp.FloatSeqHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    TemperatureApp.FloatSeqHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return TemperatureApp.FloatSeqHelper.type ();
  }

}
