package TemperatureApp;


/**
* TemperatureApp/TemperatureServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TemperatureService.idl
* Monday, 23 June 2025 04:32:24 o'clock WET
*/

public interface TemperatureServiceOperations 
{
  void sendTemperature (String id, String capteur_id, float temperature);

  /*permet à un client de récupérer les dernières températures d�"un capteur donné.*/
  float[] getLastTemperatures (String id, String capteur_id, int count);
} // interface TemperatureServiceOperations
