package TemperatureApp;

/**
* TemperatureApp/TemperatureServiceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TemperatureService.idl
* Monday, 23 June 2025 04:32:24 o'clock WET
*/

public final class TemperatureServiceHolder implements org.omg.CORBA.portable.Streamable
{
  public TemperatureApp.TemperatureService value = null;

  public TemperatureServiceHolder ()
  {
  }

  public TemperatureServiceHolder (TemperatureApp.TemperatureService initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = TemperatureApp.TemperatureServiceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    TemperatureApp.TemperatureServiceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return TemperatureApp.TemperatureServiceHelper.type ();
  }

}
