package TemperatureApp;


/**
* TemperatureApp/TemperatureServiceHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TemperatureService.idl
* Monday, 23 June 2025 04:32:24 o'clock WET
*/

abstract public class TemperatureServiceHelper
{
  private static String  _id = "IDL:TemperatureApp/TemperatureService:1.0";

  public static void insert (org.omg.CORBA.Any a, TemperatureApp.TemperatureService that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static TemperatureApp.TemperatureService extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (TemperatureApp.TemperatureServiceHelper.id (), "TemperatureService");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static TemperatureApp.TemperatureService read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_TemperatureServiceStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, TemperatureApp.TemperatureService value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static TemperatureApp.TemperatureService narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof TemperatureApp.TemperatureService)
      return (TemperatureApp.TemperatureService)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      TemperatureApp._TemperatureServiceStub stub = new TemperatureApp._TemperatureServiceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static TemperatureApp.TemperatureService unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof TemperatureApp.TemperatureService)
      return (TemperatureApp.TemperatureService)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      TemperatureApp._TemperatureServiceStub stub = new TemperatureApp._TemperatureServiceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
